version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  allow:
  - dependency-name: "github.com/gardener/gardener"
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /.test-defs
  schedule:
    interval: daily
